### PR TITLE
Build cleanup

### PR DESCRIPTION
**Pull request by Lykathia**
As part of cleaning up the docker build, made some other changes that I figured deserved their own PR.

This is largely in service of removing the need for the build.sh post script.

One potential issue:
The linter complains about the lack of double quotes, which jekyll inserts as part of it's `relative_url` expansion.
With the current setup, the linter is being run early in the build cycle, and isn't linting the generated jekyll files.

See the individual commit messages for more detail.

### CODE REVIEW

**Comment by Lykathia** [comment]
Looks like jekyll is alright with substituting double quotation, will push a fix that keeps the linter happy.

**Comment by ghost** [comment]
Sounds good, I'm quite new to jekyll the relative path stuff looks much cleaner than my hack script.

**Comment by ghost** [comment]
Changed this to `develop` branch as this is where it should go until it gets merged to master.

Will look at fixing the merge blocking later.

**Comment by Lykathia** [comment]
Another fan of git-flow? :(

**Comment by ghost** [comment]
@Lykathia seems like the move of the base to develop if i do it in the git web ui messed it up i'll bypass it soon enough.

**Comment by ghost** [comment]
Just went ahead an added `docker-compose.yml` to the ignore list in `_config.yml`.

**Comment by ghost** [comment]
Merging then prepare for rebase.

**Pull request merged**
